In [1]:
import numpy as np
import pandas as pd

In [2]:
import tensorflow as tf
print(tf.__version__)

2023-09-29 20:13:11.574309: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-09-29 20:13:11.575928: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-09-29 20:13:11.609012: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-09-29 20:13:11.609640: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-29 20:13:12.261340: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Co

2.12.0


In [3]:
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense, GRU, Embedding, CuDNNGRU
from keras.optimizers import Adam
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras.optimizers import Adam

In [5]:
!unzip "archive (3).zip"

Archive:  archive (3).zip
  inflating: dataset.csv             


In [7]:
tweets = pd.read_csv('dataset.csv')

In [8]:
tweets_data = tweets['Tweets']

In [9]:
label_data = tweets['Class']

In [10]:
tweets_data[0]

'Kahramanmaraş türkoğlu ilçesi şekeroba köyü çağrı sokak no 4 çadır yatak ısıtıcı ölen insanlae için de kefen ihtiyacı var  iletişim:05435379496'

In [11]:
label_data[0]

1.0

In [12]:
target = tweets['Class'].values.tolist()
data = tweets['Tweets'].values.tolist()

In [13]:
len(target)

499

In [14]:
target[0]

1.0

In [15]:
len(data)

499

In [16]:
data[0]

'Kahramanmaraş türkoğlu ilçesi şekeroba köyü çağrı sokak no 4 çadır yatak ısıtıcı ölen insanlae için de kefen ihtiyacı var  iletişim:05435379496'

In [17]:
cutoff = int(len(data) * 0.80) #listeyi böldük
x_train, x_test = data[:cutoff], data[cutoff:]
y_train, y_test = target[:cutoff], target[cutoff:]

In [18]:
x_train[299]

'Bir var bir yok  Onlar öğrenci tam anlamı ile çalışmadı  Bir çalışma yaptırıyorum bir yok  Nedir bu ya çocuk oyuncağı yaptınız. Ummadığınız staj mağdurları ve ailleri sandıkta deprem etkisi yaratacak  Biz çocuk değiliz seçmeniz  Sigorta geçersiz olsa da oyumuz geçerli  #OyumStaja'

In [19]:
y_train[299]

0.0

In [20]:
num_words = 500 # kelime haznemizdeki max kelime sayısı
tokenizer = Tokenizer(num_words=num_words)

In [21]:
type(data)

list

In [22]:
data = np.array(data)

In [23]:
data

array(['Kahramanmaraş türkoğlu ilçesi şekeroba köyü çağrı sokak no 4 çadır yatak ısıtıcı ölen insanlae için de kefen ihtiyacı var  iletişim:05435379496',
       'Teyitli, ses var, köpekler tepki veriyor.  Her şey var, sadece iki adet #ekskavatör lazım…  Ürgen paşa mah Atatürk cad Gül Apt 87/6  Nasrettin -Müzehher Maruf Ayda - mehmet Altay   Gassan Cilli 05322271102',
       '0539 693 27 99 bu arkadaş Kahramanmaraş’ta çadır yokmuş 20 aylık bebeği var yakın olan konumla bilgisi olan varmı yakında çadırken olur çadır getirecek olur arabasının yakıtı bitmiş askerlik arkadaşımdır kendisi',
       'Babamın yaşadığı yere henüz yardım ulaşmamış şarjlari çok az güvenligi olmayan bir alandalar kar yağıyor hipotermi gecirebilirler iletişim kurduk ateş yakamıyolar.Erzakları da yok  Kalaycik mahallesi Kalaycik sokak no:33 Islahiye/Gaziantep Elif koyuncuoglu  0539 248 9403',
       "Samsun Atakum'da 18 adet yeni eşyalı daire vardır. 8 aylık kira ve ısıtma masrafları ödenmiştir. Ulaşım için destek sa

In [24]:
tokenizer.fit_on_texts(data)

In [25]:
tokenizer.word_index

{'ve': 1,
 'deprem': 2,
 'var': 3,
 'gıda': 4,
 'bir': 5,
 'battaniye': 6,
 'çadır': 7,
 'çok': 8,
 'mahallesi': 9,
 'acil': 10,
 'hatay': 11,
 'için': 12,
 'no': 13,
 'yardım': 14,
 'lütfen': 15,
 'su': 16,
 'bu': 17,
 'aci̇l': 18,
 'köyü': 19,
 'kahramanmaraş': 20,
 'bebek': 21,
 'lazım': 22,
 'çocuk': 23,
 'bezi': 24,
 '90': 25,
 'sokak': 26,
 'ihtiyaçları': 27,
 'yok': 28,
 '4': 29,
 'powerbank': 30,
 'da': 31,
 'i̇letişim': 32,
 'mah': 33,
 'ihtiyacı': 34,
 'ped': 35,
 'de': 36,
 'mazot': 37,
 'antakya': 38,
 '1': 39,
 'olur': 40,
 'ne': 41,
 'merkez': 42,
 'yardim': 43,
 'malatya': 44,
 'ısıtıcı': 45,
 'kadar': 46,
 'teyitli': 47,
 'yardımı': 48,
 'en': 49,
 'kıyafet': 50,
 'artar': 51,
 'adıyaman': 52,
 'erzak': 53,
 'her': 54,
 'kişi': 55,
 '0': 56,
 '5': 57,
 'ile': 58,
 'kadın': 59,
 'olan': 60,
 'caddesi': 61,
 'yemek': 62,
 'çocuklar': 63,
 'teyi̇tli̇': 64,
 'gerekiyor': 65,
 'fiyatları': 66,
 '3': 67,
 'o': 68,
 '2': 69,
 'maraş': 70,
 'çadir': 71,
 'temel': 72,
 'aile': 7

In [26]:
x_train_tokens = tokenizer.texts_to_sequences(x_train)

In [27]:
x_train[10]

'K.maraş Türkoğlu Beyoğlu mahallesi yeni Adana yolu lise civarı no55 erzak çadır yardımı acil +905510103613'

In [28]:
print(x_train_tokens[10])

[70, 95, 9, 150, 390, 53, 7, 48, 10]


In [29]:
x_test = np.array(x_test)

In [30]:
x_test_tokens = tokenizer.texts_to_sequences(x_test)

In [31]:
num_tokens = [len(tokens) for tokens in x_train_tokens + x_test_tokens]
num_tokens = np.array(num_tokens)

In [32]:
np.mean(num_tokens)

15.2625250501002

In [33]:
np.max(num_tokens)

43

In [34]:
np.argmax(num_tokens)

169

In [35]:
x_train[21]

'CADIR ERZAK TEMEL GIDA ACIL Beyoğlu mahallesi istiklal caddesi Selvi sokak no :9 sağlık ocagı dönüşü köşe başı KAHRAMANMARAŞ Remzi Ercan 05330555658  Çocuk var yanlarında 10 aylık ve 4 yaşında şuanda 15 kişiler tek bir çadıra sığarız biz diyorlar  ACİL‼️‼️‼️‼️‼️‼️'

In [36]:
max_tokens = np.mean(num_tokens) + 2 * np.std(num_tokens)
max_tokens = int(max_tokens)
max_tokens

29

In [37]:
np.sum(num_tokens < max_tokens) / len(num_tokens)

0.9519038076152304

In [38]:
x_train_pad = pad_sequences(x_train_tokens, maxlen=max_tokens)

In [39]:
x_test_pad = pad_sequences(x_test_tokens, maxlen=max_tokens)

In [40]:
x_train_pad.shape

(399, 29)

In [41]:
x_test_pad.shape

(100, 29)

In [42]:
np.array(x_train_tokens[10])

array([ 70,  95,   9, 150, 390,  53,   7,  48,  10])

In [43]:
x_train_pad[10]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  70,  95,   9, 150, 390,  53,
         7,  48,  10], dtype=int32)

In [44]:
idx = tokenizer.word_index
inverse_map = dict(zip(idx.values(), idx.keys()))

In [45]:
def tokens_to_string(tokens):
    words = [inverse_map[token] for token in tokens if token!=0]
    text = ' '.join(words)
    return text

In [46]:
x_train[10]

'K.maraş Türkoğlu Beyoğlu mahallesi yeni Adana yolu lise civarı no55 erzak çadır yardımı acil +905510103613'

In [47]:
tokens_to_string(x_train_tokens[10])

'maraş türkoğlu mahallesi yeni yolu erzak çadır yardımı acil'

In [48]:
x_train_pad[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        20,  95, 126,  19,  26,  13,  29,   7, 387,  45,  12,  36, 495,
        34,   3, 107], dtype=int32)

In [49]:
model = Sequential()

In [50]:
embedding_size = 100

In [51]:
model.add(Embedding(input_dim=num_words,
                    output_dim=embedding_size,
                    input_length=max_tokens,
                    name='embedding_layer'))

In [52]:
model.add(GRU(units=16, return_sequences=True))
model.add(GRU(units=8, return_sequences=True))
model.add(GRU(units=4))
model.add(Dense(1, activation='sigmoid'))

In [53]:
optimizer = Adam(learning_rate=1e-3)

In [54]:
from keras.losses import binary_crossentropy
lss = binary_crossentropy

In [55]:
model.compile(optimizer= 'adam' , loss= lss, metrics=['accuracy'])

In [56]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_layer (Embedding)  (None, 29, 100)           50000     
_________________________________________________________________
gru (GRU)                    (None, 29, 16)            5616      
_________________________________________________________________
gru_1 (GRU)                  (None, 29, 8)             600       
_________________________________________________________________
gru_2 (GRU)                  (None, 4)                 156       
_________________________________________________________________
dense (Dense)                (None, 1)                 5         
Total params: 56,377
Trainable params: 56,377
Non-trainable params: 0
_________________________________________________________________


In [57]:
y_train = np.array(y_train)
x_train = np.array(x_train)

In [58]:
type(x_train)

numpy.ndarray

In [59]:
x_train[0]

'Kahramanmaraş türkoğlu ilçesi şekeroba köyü çağrı sokak no 4 çadır yatak ısıtıcı ölen insanlae için de kefen ihtiyacı var  iletişim:05435379496'

In [60]:
model.fit(x_train_pad, y_train, epochs=5, batch_size=32)

Epoch 1/5
13/13 [==============================] - 4s 24ms/step - loss: 0.6682 - accuracy: 0.7193
Epoch 2/5
13/13 [==============================] - 0s 24ms/step - loss: 0.5778 - accuracy: 0.7544
Epoch 3/5
13/13 [==============================] - 0s 24ms/step - loss: 0.4373 - accuracy: 0.8371
Epoch 4/5
13/13 [==============================] - 0s 26ms/step - loss: 0.2802 - accuracy: 0.9449
Epoch 5/5
13/13 [==============================] - 0s 28ms/step - loss: 0.1681 - accuracy: 0.9825


In [61]:
y_test = np.array(y_test)

In [62]:
result = model.evaluate(x_test_pad, y_test)

4/4 [==============================] - 0s 6ms/step - loss: 0.2134 - accuracy: 0.9700


In [63]:
result[1]

0.9700000286102295

In [64]:
y_pred = model.predict(x=x_test_pad[0:1000])
y_pred = y_pred.T[0]# stünları satırlara çeviriyoruz

In [65]:
cls_pred = np.array([1.0 if p>0.5 else 0.0 for p in y_pred])

In [66]:
cls_true = np.array(y_test[0:1000])

In [67]:
incorrect = np.where(cls_pred != cls_true)
incorrect = incorrect[0]

In [68]:
len(incorrect)

3

In [69]:
idx = incorrect[0]
idx

9

In [70]:
text = x_test[idx]
text

'Malatya fay zonu ile Maraş Türkoğlu ve pazarcık segmenti oluşturabiliceği maksimum Yer sarsıntısı(Deprem) 7.2 ve bunun için acilen o bölge için gerekli tedbirlerin alınması gerek.'

In [71]:
y_pred[idx]

0.55449873

In [72]:
cls_true[idx]

0.0

In [73]:
text1 = "Kahramanmaraş türkoğlu ilçesi şekeroba köyü çağrı sokak no 4 çadır yatak ısıtıcı ölen insanlae için de kefen ihtiyacı var."
text2 = "binalar yıkıldı su, çadır ve yemeğe ihtiyaç var yardım edin"
text3 = "bu gün günlerden pazartesi ve çok yorgunum berikadan nefret ediyorum malın teki"

texts = [text1, text2, text3]


In [74]:
tokens = tokenizer.texts_to_sequences(texts)

In [75]:
tokens_pad = pad_sequences(tokens, maxlen=max_tokens)
tokens_pad.shape

(3, 29)

In [76]:
arr = model.predict(tokens_pad)

In [77]:
arr

array([[0.91471684],
       [0.794945  ],
       [0.16300316]], dtype=float32)

In [1]:
for a in arr:
  if(a>0.70):
    print("yardım çağrısı içeren bir cümle")
  elif(a<0.70):
    print("alakasız bir cümle")

NameError: name 'arr' is not defined

In [79]:
model.save('help.h5')

In [ ]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By

In [ ]:
page="https://twitter.com/i/flow/login"
USER = "username"
PASSWORD = "password"

In [ ]:
while True:
    try:
        driver = webdriver.Firefox()
        driver.get(page)
        time.sleep(15)

        driver.find_element(By.XPATH, '/html/body/div/div/div/div[1]/div/div/div/div/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div/div/div/div[5]/label/div/div[2]/div/input').click
        username_input = driver.find_element(By.XPATH, '/html/body/div/div/div/div[1]/div/div/div/div/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div/div/div/div[5]/label/div/div[2]/div/input')
        username_input.send_keys(USER)                 #"/html/body/div/div/div/div[1]/div/div/div/div/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div/div/div/div[5]/label/div/div[2]/div/input"
        time.sleep(4)
        login_button = driver.find_element(By.XPATH, '/html/body/div[1]/div/div/div[1]/div/div/div/div/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div/div/div/div[6]')
        login_button.click()


        time.sleep(5)

        password_input = driver.find_element(By.XPATH, '/html/body/div/div/div/div[1]/div/div/div/div/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div[1]/div/div/div[3]/div/label/div/div[2]/div[1]/input')
        password_input.send_keys(PASSWORD)
        time.sleep(4)
        # find the element for login and click on it
        login_button = driver.find_element(By.XPATH, '/html/body/div/div/div/div[1]/div/div/div/div/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div[2]/div/div[1]/div/div/div')
        login_button.click()                         #"/html/body/div/div/div/div[1]/div/div/div/div/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div/div/div/div[6]/div"

        hastag = "deprem"
        hastag_url = f"https://twitter.com/search?q=%23{hastag}&src=typed_query&f=live"
        #print(hastag_url)
        time.sleep(5)
        driver.get(hastag_url)
        time.sleep(5)
        run_timer = 0
        temp_text = " "
        tweet = ""
        while True:
            run_timer += 1
            for scrool in range(3):
                driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
                time.sleep(3)
            time.sleep(5)
            for i in range(10):
                try:
                    tweet = driver.find_element(By.XPATH, f'/html/body/div[1]/div/div/div[2]/main/div/div/div/div[1]/div/div[3]/section/div/div/div[{i}]/div/div/article/div/div/div[2]/div[2]/div[2]/div/span[1]').text            # "/html/body/div[1]/div/div/div[2]/main/div/div/div/div[1]/div/div[3]/section/div/div/div[4]/div/div/article/div/div/div[2]/div[2]/div[2]/div/span[1]"
                    tokens = tokenizer.texts_to_sequences(texts)
                    tokens_pad = pad_sequences(tokens, maxlen=max_tokens)
                    #tokens_pad.shape
                    arr = model.predict(tokens_pad)
                    for a in arr:
                        if(a>0.70):
                            print("Help")
                        elif(a<0.70):
                            pass
                    print("- ",tweet)

                except:
                    pass
            if temp_text == tweet:
                break
            temp_text = tweet

    except KeyboardInterrupt:
        break
        sys.exit(0)
    except:
        pass
